packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
  better-sqlite3: true

ignoredOptionalDependencies:
  - "@mongodb-js/zstd"
  - "node-liblzma"

onlyBuiltDependencies:
  - better-sqlite3
