/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteImport } from './routes/(app)/_'
import { Route as authRouteImport } from './routes/(auth)/_'
import { Route as appIndexRouteImport } from './routes/(app)/_/index'
import { Route as appMembersRouteImport } from './routes/(app)/_/members'
import { Route as appSettingsRouteImport } from './routes/(app)/_/settings'
import { Route as authSelectOrgRouteImport } from './routes/(auth)/_/select-org'
import { Route as authSignInRouteImport } from './routes/(auth)/_/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/_/sign-up'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/_/settings/index'
import { Route as appSettingsPreferencesRouteImport } from './routes/(app)/_/settings/preferences'
import { Route as appSettingsProfileRouteImport } from './routes/(app)/_/settings/profile'
import { Route as authAcceptInvitationInvitationIdRouteImport } from './routes/(auth)/_/accept-invitation/$invitationId'

const appRoute = appRouteImport.update({
  id: '/(app)/_',
  getParentRoute: () => rootRouteImport,
} as any)
const authRoute = authRouteImport.update({
  id: '/(auth)/_',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRoute,
} as any)
const appMembersRoute = appMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => appRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRoute,
} as any)
const authSelectOrgRoute = authSelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => authRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsPreferencesRoute = appSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsProfileRoute = appSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appSettingsRoute,
} as any)
const authAcceptInvitationInvitationIdRoute =
  authAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => authRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/members': typeof appMembersRoute
  '/settings': typeof appSettingsRouteWithChildren
  '/select-org': typeof authSelectOrgRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appIndexRoute
  '/settings/preferences': typeof appSettingsPreferencesRoute
  '/settings/profile': typeof appSettingsProfileRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/settings/': typeof appSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/members': typeof appMembersRoute
  '/select-org': typeof authSelectOrgRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appIndexRoute
  '/settings/preferences': typeof appSettingsPreferencesRoute
  '/settings/profile': typeof appSettingsProfileRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/settings': typeof appSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_': typeof appRouteWithChildren
  '/(auth)/_': typeof authRouteWithChildren
  '/(app)/_/members': typeof appMembersRoute
  '/(app)/_/settings': typeof appSettingsRouteWithChildren
  '/(auth)/_/select-org': typeof authSelectOrgRoute
  '/(auth)/_/sign-in': typeof authSignInRoute
  '/(auth)/_/sign-up': typeof authSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_/': typeof appIndexRoute
  '/(app)/_/settings/preferences': typeof appSettingsPreferencesRoute
  '/(app)/_/settings/profile': typeof appSettingsProfileRoute
  '/(auth)/_/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/(app)/_/settings/': typeof appSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/members'
    | '/settings'
    | '/select-org'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/'
    | '/settings/preferences'
    | '/settings/profile'
    | '/accept-invitation/$invitationId'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/members'
    | '/select-org'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/'
    | '/settings/preferences'
    | '/settings/profile'
    | '/accept-invitation/$invitationId'
    | '/settings'
  id:
    | '__root__'
    | '/(app)/_'
    | '/(auth)/_'
    | '/(app)/_/members'
    | '/(app)/_/settings'
    | '/(auth)/_/select-org'
    | '/(auth)/_/sign-in'
    | '/(auth)/_/sign-up'
    | '/api/auth/$'
    | '/(app)/_/'
    | '/(app)/_/settings/preferences'
    | '/(app)/_/settings/profile'
    | '/(auth)/_/accept-invitation/$invitationId'
    | '/(app)/_/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  authRoute: typeof authRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/_': {
      id: '/(app)/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_': {
      id: '/(auth)/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_/': {
      id: '/(app)/_/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_/members': {
      id: '/(app)/_/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof appMembersRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_/settings': {
      id: '/(app)/_/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRoute
    }
    '/(auth)/_/select-org': {
      id: '/(auth)/_/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof authSelectOrgRouteImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_/sign-in': {
      id: '/(auth)/_/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_/sign-up': {
      id: '/(auth)/_/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_/settings/': {
      id: '/(app)/_/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/_/settings/preferences': {
      id: '/(app)/_/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof appSettingsPreferencesRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/_/settings/profile': {
      id: '/(app)/_/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof appSettingsProfileRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(auth)/_/accept-invitation/$invitationId': {
      id: '/(auth)/_/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof authAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof authRoute
    }
  }
}

interface appSettingsRouteChildren {
  appSettingsPreferencesRoute: typeof appSettingsPreferencesRoute
  appSettingsProfileRoute: typeof appSettingsProfileRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appSettingsRouteChildren: appSettingsRouteChildren = {
  appSettingsPreferencesRoute: appSettingsPreferencesRoute,
  appSettingsProfileRoute: appSettingsProfileRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appSettingsRouteWithChildren = appSettingsRoute._addFileChildren(
  appSettingsRouteChildren,
)

interface appRouteChildren {
  appMembersRoute: typeof appMembersRoute
  appSettingsRoute: typeof appSettingsRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteChildren: appRouteChildren = {
  appMembersRoute: appMembersRoute,
  appSettingsRoute: appSettingsRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authRouteChildren {
  authSelectOrgRoute: typeof authSelectOrgRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authAcceptInvitationInvitationIdRoute: typeof authAcceptInvitationInvitationIdRoute
}

const authRouteChildren: authRouteChildren = {
  authSelectOrgRoute: authSelectOrgRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authAcceptInvitationInvitationIdRoute: authAcceptInvitationInvitationIdRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  authRoute: authRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
